#!/usr/bin/env python3
"""
sync-skills.py — generate skills.json from catalog.config.json.

For each skill listed under "mine", reads its SKILL.md frontmatter and fills in
`name`, `summary` and `use_when` automatically (so you never retype a description).
The curated fields — ref / tags / repo / install / status — come from the config.
Anything you set explicitly in the config wins over the auto-pulled value.

Usage:
    python3 scripts/sync-skills.py            # regenerate skills.json
    python3 scripts/sync-skills.py --check    # fail if skills.json is out of date

The skill folder defaults to ~/.claude/skills/<slug>; override with "skill_dir".
"""
from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONFIG = os.path.join(ROOT, "catalog.config.json")
OUTPUT = os.path.join(ROOT, "skills.json")

# tokens to uppercase when prettifying a slug into a display name
ACRONYMS = {
    "amt", "pas", "iptv", "av", "pdf", "boq", "kfuh", "css", "json",
    "en", "ar", "rtl", "hdmi", "dvb", "oem", "ui", "ux", "api", "cli",
}


def parse_frontmatter(path: str) -> dict:
    """Read YAML-ish frontmatter (--- ... ---). Tolerates quoted/unquoted values."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    fields = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        val = val.strip()
        if (val.startswith('"') and val.endswith('"')) or (
            val.startswith("'") and val.endswith("'")
        ):
            val = val[1:-1]
        fields[key.strip()] = val.strip()
    return fields


def prettify(slug: str) -> str:
    words = re.split(r"[-_\s]+", slug)
    out = []
    for w in words:
        out.append(w.upper() if w.lower() in ACRONYMS else w.capitalize())
    return " ".join(out)


def split_summary(description: str) -> tuple[str, str | None]:
    """Split a SKILL.md description into (summary, use_when) on 'Use when'."""
    m = re.search(r"\bUse when\b[:\s]*", description, re.IGNORECASE)
    if not m:
        return description.strip(), None
    summary = description[: m.start()].strip().rstrip(".").strip() + "."
    use_when = description[m.end():].strip()
    if use_when:
        use_when = use_when[0].upper() + use_when[1:]
    return summary, (use_when or None)


def build_mine(entry: dict) -> dict | None:
    slug = entry["slug"]
    skill_dir = os.path.expanduser(
        entry.get("skill_dir", f"~/.claude/skills/{slug}")
    )
    skill_md = os.path.join(skill_dir, "SKILL.md")

    fm = parse_frontmatter(skill_md) if os.path.isfile(skill_md) else {}
    if not fm:
        print(f"  ! {slug}: SKILL.md frontmatter not found at {skill_md} "
              f"— using config values only.")
    desc = fm.get("description", "")
    auto_summary, auto_use_when = split_summary(desc) if desc else ("", None)

    name = entry.get("name") or (
        prettify(fm["name"]) if fm.get("name") else prettify(slug)
    )
    summary = entry.get("summary") or auto_summary
    use_when = entry.get("use_when", auto_use_when)

    card = {
        "slug": slug,
        "ref": entry.get("ref", ""),
        "name": name,
        "summary": summary,
        "use_when": use_when,
        "tags": entry.get("tags", []),
        "repo": entry.get("repo", ""),
        "install": entry.get("install", ""),
        "status": entry.get("status", "public"),
    }
    if card["use_when"] is None:
        del card["use_when"]
    src = "SKILL.md" if desc else "config"
    print(f"  ✓ {slug}: '{name}' (summary from {src})")
    return card


def generate(config: dict) -> dict:
    print("Syncing skills from SKILL.md frontmatter …")
    mine = [c for c in (build_mine(e) for e in config.get("mine", [])) if c]
    return {
        "_note": "GENERATED by scripts/sync-skills.py from catalog.config.json — edit the config, not this file.",
        "owner": config.get("owner", {}),
        "mine": mine,
        "uses": config.get("uses", []),
    }


def main() -> int:
    check = "--check" in sys.argv
    with open(CONFIG, encoding="utf-8") as fh:
        config = json.load(fh)
    result = generate(config)
    rendered = json.dumps(result, ensure_ascii=False, indent=2) + "\n"

    if check:
        current = open(OUTPUT, encoding="utf-8").read() if os.path.isfile(OUTPUT) else ""
        if current != rendered:
            print("✗ skills.json is OUT OF DATE — run: python3 scripts/sync-skills.py")
            return 1
        print("✓ skills.json is up to date.")
        return 0

    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {OUTPUT} — {len(result['mine'])} mine, {len(result['uses'])} uses.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
